language: cpp
dist: bionic
compiler: gcc

install: 
  - sudo apt update -qq
  # Boost
  - sudo apt install -qq libboost-all-dev
  # Qt5
  - sudo apt-get install -qq qt5-qmake qt5-default
  # Qwt
  - sudo apt install -qq libqwt-qt5-dev
  # Codecov
  - sudo pip install codecov
  # OCLint
  - ./install_oclint.sh
  # Others
  - ./download_other_githubs.sh
  - ./install_other_githubs.sh

services:
 - xvfb

script: 
  # Build and start test
  - qmake BinaryNewickVectorTest.pro
  - make debug --silent
  - ./BinaryNewickVectorTest
  # Get code coverage
  - ./get_code_cov.sh >/dev/null
  - codecov >/dev/null
  # Build the demo
  - qmake TestBinaryNewickVectorDesktop.pro
  - make --silent
  # OCLint
  - ./do_oclint.sh


after_success: 
  - bash <(curl -s https://codecov.io/bash)

